<?php

namespace AppBundle\Repository;

/**
 * UrlTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
