<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 15/10/17
 * Time: 00:00
 */

namespace AppBundle\DataFixtures\ORM;


use AppBundle\Entity\Niveau;
use AppBundle\Entity\Sequence;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

class SequenceFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {

        $sequences = [["title" => "Séquence 1",
            "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
            "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
            "Level" => 0],
            ["title" => "Séquence 2",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 0],
            ["title" => "Séquence 3",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 0],
            ["title" => "Séquence 4",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 0],
            ["title" => "Séquence 1",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 1],
            ["title" => "Séquence 2",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 1],
            ["title" => "Séquence 3",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 1],
            ["title" => "Séquence 4",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 1],
            ["title" => "Séquence 1",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 2],
            ["title" => "Séquence 2",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 2],
            ["title" => "Séquence 3",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 2],
            ["title" => "Séquence 4",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 2],
            ["title" => "Séquence 1",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 3],
            ["title" => "Séquence 2",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 3],
            ["title" => "Séquence 3",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 3],
            ["title" => "Séquence 4",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 3],
            ["title" => "Séquence 1",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 4],
            ["title" => "Séquence 2",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 4],
            ["title" => "Séquence 3",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 4],
            ["title" => "Séquence 4",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 4],
            ["title" => "Séquence 1",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 5],
            ["title" => "Séquence 2",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 5],
            ["title" => "Séquence 3",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 5],
            ["title" => "Séquence 4",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 5],
            ["title" => "Séquence 1",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 6],
            ["title" => "Séquence 2",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 6],
            ["title" => "Séquence 3",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 6],
            ["title" => "Séquence 4",
                "Summary" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dui lectus, elementum et pulvinar nec, viverra tincidunt mauris. Vivamus at accumsan lacus. Quisque congue nisl justo, a vehicula dolor posuere sit amet. Donec et eros finibus nisi suscipit tristique. Nullam finibus euismod rhoncus. Etiam magna sapien, facilisis eget porta sed, porta id ipsum. Ut non orci id ex varius iaculis et id odio. Nunc fringilla orci ut quam aliquet, nec finibus orci porttitor. Donec laoreet suscipit erat id sollicitudin. Vivamus sed mattis tortor. Etiam laoreet quis velit sit amet rutrum. Etiam pretium odio hendrerit, imperdiet massa sed, pellentesque urna. Donec gravida tellus a egestas ultrices. Nullam ut risus malesuada, condimentum ligula vitae, mattis velit. Sed semper felis vitae hendrerit blandit. Aenean egestas nisi felis, non hendrerit velit iaculis ut.
Donec nec felis arcu. In sed malesuada felis, id gravida sapien. Proin faucibus nisl sit amet orci imperdiet hendrerit at eu libero. Sed blandit nulla vitae pretium gravida. Quisque vel arcu ut risus rutrum imperdiet id ac nunc. Suspendisse cursus lacus vel urna tincidunt convallis. Morbi in nunc elit. Cras a fermentum ipsum. Donec pellentesque ante nec ante lacinia eleifend ut bibendum nulla.",
                "Comment" => "Vestibulum vel erat magna. Sed consequat bibendum dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus quis odio id eros semper fringilla eget ac eros. Curabitur ut placerat ligula. Integer pulvinar est posuere diam luctus elementum. Fusce nec lorem finibus, auctor dui at, convallis dolor. Sed in congue dolor.",
                "Level" => 6]];


        foreach ($sequences as $sequence) {
            $section = new Sequence();
            $section->setTitle($sequence['title']);
            $section->setSummary($sequence['Summary']);
            $section->setComment($sequence['Comment']);
            $section->setLevel($this->getReference("level" . $sequence["Level"]));
            $section->setInstitution($this->getReference("etabl" . rand(0, 2)));
            $section->addCategory($this->getReference("category".rand(0,2)));
            $section->addUrl($this->getReference("url" . rand(0, 3)));
            $manager->persist($section);
        }

        $manager->flush();
    }

    public function getDependencies()
    {
        return array(
            UrlFixtures::class
        );
    }

}